Markdown plugin
ONLYOFFICE/docspace-plugins pull request #2
Opened 2024-01-26 11:33 UTC by sshakndr

Plugin for editing and viewing .md files.

2024-01-30 08:52 UTC, LinneyS requested changes

2024-01-30 08:52 UTC, LinneyS commented on markdown/README.md
> +
@kseniafedoruk

2024-01-30 08:54 UTC, LinneyS requested changes

2024-01-30 08:54 UTC, LinneyS commented on markdown/src/properties.json
> +    "hlstyles_url": "https://cdn.jsdelivr.net/highlight.js/9.1.0/styles/github.min.css",
take it into plugin

2024-02-01 04:35 UTC, TimofeyBoyko commented on markdown/package.json
> +    "@types/markdown-it": "^13.0.7",
Its must be in the devDependencies

2024-03-21 09:44 UTC, merged